#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NUMBER_OF_COLUMNS 7
#define NUMBER_OF_ROWS 6
#define FIELD_WIDTH 100
#define FIELD_HEIGHT 100
#define FIELD_WIDTH_OFFSET 0
#define FIELD_HEIGHT_OFFSET 0
#define BLOCK_HEIGHT 90
#define BLOCK_WIDTH 90
#define VERY_SLOW_ANIMATION_SPEED 600
#define SLOW_ANIMATION_SPEED 400
#define MEDIUM_ANIMATION_SPEED 300
#define FAST_ANIMATION_SPEED 200
#define VERY_FAST_ANIMATION_SPEED 100
#define INSTANT_ANIMATION_SPEED 0

#endif // CONSTANTS_H
